### ISSUE TITLE
using non-split configuration scheme

### ISSUE THREAD

**Issue by laouache** [namshi/docker-smtp#13]
Hi, 

I have an issue with last updates when i launch this command :

```
docker run --name smtp     -p 25:25     -e GMAIL_USER="Xxxx@x...."     -e GMAIL_PASSWORD="XXXX"     -e RELAY_NETWORKS=":192.168.0.0/24"     docker-smtp     --restart=always     --rm
+ sed -ri '
    s/^#?(dc_local_interfaces)=.*/\1='\''[0.0.0.0]:25 ; [::0]:25'\''/;
    s/^#?(dc_other_hostnames)=.*/\1='\'''\''/;
    s/^#?(dc_relay_nets)=.*/\1='\''172.17.0.2\/16:192.168.0.0\/24'\''/;
    s/^#?(dc_eximconfig_configtype)=.*/\1='\''smarthost'\''/;
    s/^#?(dc_smarthost)=.*/\1='\''smtp.gmail.com::587'\''/;
' /etc/exim4/update-exim4.conf.conf
+ update-exim4.conf -v
using non-split configuration scheme from /etc/exim4/exim4.conf.template
/bin/entrypoint.sh: line 54: exec: --: invalid option
exec: usage: exec [-cl] [-a name] [command [arguments ...]] [redirection ...]
```

I tried some syntax but allways the same error message.

What do you think ?

**Comment by oba11** [comment]
Hello @laouache, tried the below command and works for me with the latest build from docker hub

```
docker run --name smtp -p 25:25 -e GMAIL_USER="Xxxx@x...." -e GMAIL_PASSWORD="XXXX" -e RELAY_NETWORKS=":192.168.0.0/24" --restart=always namshi/smtp
```

I think the likely issue would be `docker-smtp  --restart=always  --rm` in your command argument. 
We are using combination of entry point and cmd in the dockerfile, anything you write after the image name is passed as a command argument. If you move the `--restart=always  --rm` to the front of the image name should work also u can't combine `--rm` and `--restart=always`. Hope this helps

**Comment by laouache** [comment]
Hi, 

Thanks it works. I know for rm , it was a for test. Thanks again.

**Comment by oba11** [comment]
you are welcome
