### ISSUE TITLE
How do I send mails with this?

### ISSUE THREAD

**Issue by miguelglopes** [namshi/docker-smtp#17]
I have the image running with gmail user and gmail password set. How do I send mails now?

**Comment by oba11** [comment]
U can easily test by using default linux `mail` command (assuming the container is running on 127.0.0.1:25).

**Comment by oba11** [comment]
You can send automated email with this python script (https://gist.github.com/oba11/3446f6f519b7e09c9d4e45728f73799e) as well.
Hope this helps.
