### ISSUE TITLE
explain on how to extend this container with own configurations

### ISSUE THREAD

**Issue by domdorn** [namshi/docker-smtp#23]
Hi,

it would be great if you could write a sentence or two on how to integrate own configurations into the container. 

If managed to get DKIM working by bind-mounting over the generated exim4.conf.localmacros like
      - ./00_local_macros.txt:/etc/exim4/exim4.conf.localmacros:ro
however, now I want to add a new config that would add VERP by mounting it into
      - ./verp.conf:/etc/exim4/conf.d/rewrite/40_exim4-config_verp
but as the container is using a single-config file, it won't pick up this config. 
I don't want to bind-mount the whole config file into the container, as then I would lose the flexibility gained by your sed-replacements (ips and so on..) 

any hints / suggestions are highly appreciated!

**Comment by oba11** [comment]
@domdorn mounting custom confguration is not supported because it needs to be included in the custom config. PRs are always welcome to support it.
Thanks

**Comment by domdorn** [comment]
sent a PR, please see
https://github.com/namshi/docker-smtp/pull/27

would be great if you could review it and push a new version!

thx

**Comment by oba11** [comment]
@domdorn the PR has been merged, would be closing this issue.
Thanks
