### ISSUE TITLE
gmail relay triggers 'blocked sign-in attempt'

### ISSUE THREAD

**Issue by dsummersl** [namshi/docker-smtp#24]
Not totally sure why this is, but I have to 'allow less secure apps' in order to use the gmail relay setting. I get an email like:

```
Hi XXX,
Google just blocked someone from signing into your Google Account XXX@gmail.com from an app that may put your account at risk.
Less secure app
Friday, March 10, 2017 10:41 AM (EST)
Ashburn, VA, USA*
Don't recognize this activity?
If you didn't recently receive an error while trying to access a Google service, like Gmail, from a non-Google application, someone may have your password.

SECURE YOUR ACCOUNT

Are you the one who tried signing in?
Google will continue to block sign-in attempts from the app you're using because it has known security problems or is out of date. You can continue to use this app by allowing access to less secure apps, but this may leave your account vulnerable.

Best,
The Google Accounts team
```

**Comment by oba11** [comment]
@dsummersl not sure why it's happening with your account, probably too many email from account which are not secure. Tried it with my gmail account which works seemlessly though I have 2-factor authentication enabled (without turning on less secure apps). 

You may want to turn on 2fa on your account or turn on [less secure apps](https://support.google.com/accounts/answer/6010255?hl=en) to see if it works.

I'm closing this issue but feel free to reopen it if the issue persist.
Thanks.
