### ISSUE TITLE
How to configure exim4 within your container as a simple smtp server

### ISSUE THREAD

**Issue by MarcinKowal** [namshi/docker-smtp#25]
Hi, 
I was trying to use your container as a simple smtp server (without any relay). I've build the image from source and successfully ran it. The question is how can I configure it. Thought I can use the following command 
sudo dpkg-reconfigure exim4-config but unfortunetely not able to attach to the running container, even when it was started with -itd options.

**Comment by oba11** [comment]
@MarcinKowal The image if preconfigured to work with (without relay option) so no need to do custom configuration.

To work as a simple SMTP server, it works as below

```
:~$ docker run -it -p 25:25 namshi/smtp

:~$ echo "This is a test" | mail -s "Test" mail@example.com

```

This works for me, and you can also try [this python script](https://gist.github.com/oba11/3446f6f519b7e09c9d4e45728f73799e) to test it with works as well.

I'm going to close the issue and please feel free to reopen it if the solution above doesn’t work. Thanks
