### ISSUE TITLE
Google Cloud - Amazon SES Porting

### ISSUE THREAD

**Issue by rjpalermo1** [namshi/docker-smtp#7]
Hi, I really appreciate this image and am now trying to get it working on my Google Cloud VPS.  As you may already know, they block the normal outgoing ports for SMTP.  As I was figuring this out, I ran across this stackof:  http://stackoverflow.com/questions/24834047/amazon-ses-on-google-cloud-computing-instance-vm-using-postfix

Is this possible to include in your .sh?

**Comment by oba11** [comment]
Hello @rjpalermo1, have you tried switching the docker host port? I mean instead of doing `docker run -p 25:25 namshi/smtp`, you can try `docker run -p 2587:25 namshi/smtp` to see if it works out for you.
Thanks.

**Comment by MartijnVdS** [comment]
I'm not the original reporter, but we had a similar issue in our setup: our service discovery tools look at the "internal" port number in the container, and expose that on every machine in our cluster. This allows all machines to connect to :<port> on their host.

We run a separate SMTP daemon for incoming mail on port 25, which works great, but I can't also run this container on port 25 (even if I use "-p 2525:25", our service discovery tools expose "25" on the cluster).

I've submitted a pull request to allow setting the port Exim listens on using something like "--env=PORT=2525" on the "docker run" commandline, which should help handle this problem

**Comment by oba11** [comment]
Thanks @MartijnVdS for the https://github.com/namshi/docker-smtp/pull/11, good to merge once we remove the expose option in the dockerfile

**Comment by oba11** [comment]
@rjpalermo1 pls can u test if this PR https://github.com/namshi/docker-smtp/pull/11 resolves this issue

**Comment by rjpalermo1** [comment]
Hi and thank you for your attention.  I am out of country right now and
will be back May 18th.  Will check then and report back.

Best regards and thank you again,

_Russ Palermo_
Founder | TekTango LLC

office:    866-505-5066 x700
mobile:  317-454-1099

On Tue, May 10, 2016 at 6:26 AM, Oluwaseun Obajobi <notifications@github.com
