### ISSUE TITLE
Cannot send email messages

### ISSUE THREAD

**Issue by thetealover** [namshi/docker-smtp#70]
The destination email provider in the provided logs is outlook.com. Sending messages to Gmail also failed. No environment variables configured.
Here are the logs:
```
+ sed -ri '
        s/^#?(dc_local_interfaces)=.*/\1='\''[0.0.0.0]:25 ; [::0]:25'\''/;
        s/^#?(dc_other_hostnames)=.*/\1='\'''\''/;
        s/^#?(dc_relay_nets)=.*/\1='\''172.17.0.2\/16'\''/;
        s/^#?(dc_eximconfig_configtype)=.*/\1='\''internet'\''/;
' /etc/exim4/update-exim4.conf.conf
+ update-exim4.conf -v
using non-split configuration scheme from /etc/exim4/exim4.conf.template
    1 LOG: MAIN
    1   exim 4.92 daemon started: pid=1, -q15m, listening for SMTP on port 25 (IPv6 and IPv4)
  273 LOG: host_lookup_failed MAIN
  273   no host name found for IP address 172.17.0.1
  273 LOG: MAIN
  273   <= printer-no-reply@gmail.com H=(SFL4819L470.sflpro.local) [172.17.0.1] P=esmtp S=459
  273 LOG: smtp_connection MAIN
  273   SMTP connection from (SFL4819L470.sflpro.local) [172.17.0.1] lost D=0s
  274 Exim version 4.92 uid=101 gid=101 pid=274 D=80001
Berkeley DB: Berkeley DB 5.3.28: (September  9, 2013)
Support for: crypteq iconv() IPv6 GnuTLS move_frozen_messages DANE DKIM DNSSEC Event OCSP PRDR SOCKS TCP_Fast_Open
Lookups (built-in): lsearch wildlsearch nwildlsearch iplsearch cdb dbm dbmjz dbmnz dnsdb dsearch nis nis0 passwd
Authenticators: cram_md5 plaintext
Routers: accept dnslookup ipliteral manualroute queryprogram redirect
Transports: appendfile/maildir/mailstore autoreply lmtp pipe smtp
Fixed never_users: 0
Configure owner: 0:0
Size of off_t: 8
  274 delivering 1jfP9W-00004P-G7
  274 R: dnslookup for arthur.hakobyan@live.com
  275 T: remote_smtp for arthur.hakobyan@live.com
  275 Connecting to live-com.olc.protection.outlook.com [104.47.66.33]:25 ... failed: Connection refused
  275 LOG: MAIN
  275   H=live-com.olc.protection.outlook.com [104.47.66.33] Connection refused
  275 Connecting to live-com.olc.protection.outlook.com [104.47.55.161]:25 ... failed: Connection refused
  275 LOG: MAIN
  275   H=live-com.olc.protection.outlook.com [104.47.55.161] Connection refused
  274 LOG: MAIN
  274   == arthur.hakobyan@live.com R=dnslookup T=remote_smtp defer (111): Connection refused
```

**Comment by cottonthread** [comment]
Can you use telnet from the host like `telnet live-com.olc.protection.outlook.com 25`and passthrough? I think is your vps provider blocking you.

Me using telnet:


```
Trying 104.47.55.161...
Connected to live-com.olc.protection.outlook.com.
Escape character is '^]'.
220 BN8NAM12FT014.mail.protection.outlook.com Microsoft ESMTP MAIL Service ready at Mon, 1 Jun 2020 22:36:12 +0000
help
214-This server supports the following commands:
214 HELO EHLO STARTTLS RCPT DATA RSET MAIL QUIT HELP AUTH BDAT
quit
```

**Comment by thetealover** [comment]
I think it might be. I called my ISP and asked if they are blocking the 25 port and they said that they are not. Do you think that they gave me an incorrect answer?

Windows power shell:
`Connecting To live-com.olc.protection.outlook.com...Could not open connection to the host, on port 25: Connect failed`

Ubuntu terminal:
`telnet live-com.olc.protection.outlook.com 25
Trying 104.47.38.33...
Trying 104.47.37.33...
telnet: Unable to connect to remote host: Resource temporarily unavailable`

**Comment by cottonthread** [comment]
> I think it might be. I called my ISP and asked if they are blocking the 25 port and they said that they are not. Do you think that they gave me an incorrect answer?
> 
> Windows power shell:
> `Connecting  live-com.olc.protection.outlook.com...Could not open connection to the host, on port 25: Connect failed`
> 
> Ubuntu terminal:
> `telnet live-com.olc.protection.outlook.com 25
> Trying 104.47.38.33...
> Trying 104.47.37.33...
> telnet: Unable to connect to remote host: Resource temporarily unavailable`

I think they are blocking your 25, at least on your outgoing conections from host, now try do some incoming test to verify if they are blocking it too by doing an telnet or whatever from out side to your host. If you have same result, they are blocking you 😅

**Comment by cottonthread** [comment]
> I think it might be. I called my ISP and asked if they are blocking the 25 port and they said that they are not. Do you think that they gave me an incorrect answer?
> 
> Windows power shell:
> `Connecting  live-com.olc.protection.outlook.com...Could not open connection to the host, on port 25: Connect failed`
> 
> Ubuntu terminal:
> `telnet live-com.olc.protection.outlook.com 25
> Trying 104.47.38.33...
> Trying 104.47.37.33...
> telnet: Unable to connect to remote host: Resource temporarily unavailable`

I think they are blocking your 25, at least on your outgoing conections from host, now try do some incoming test to verify if they are blocking it too by doing an telnet or whatever from out side to your host. If you have same result, they are blocking you 😅

**Comment by thetealover** [comment]
Thank you.
