### ISSUE TITLE
Restart of container causes an error

### ISSUE THREAD

**Issue by msroest** [namshi/docker-smtp#8]
If docker has to restart a running container (server reboot, docker service restart)

The container is not able to come back up.

I think this was caused by my changes for #5 .

Adding this as a placeholder so people know there is an issue and I'm looking into it.

Error:
2016-04-28 23:20:35 Exim configuration error:
  macro "MAIN_HARDCODE_PRIMARY_HOSTNAME" is already defined (use "==" if you want to redefine it
Invalid new configfile /var/lib/exim4/config.autogenerated.tmp, not installing

**Comment by oba11** [comment]
thanks for the catch @msroest , just noticed it as well.
I think one easy way could be changing the io redirection from `>>` to `>` [here](https://github.com/namshi/docker-smtp/blob/master/entrypoint.sh#L5).

**Comment by msroest** [comment]
That looks like it.  I'll try to get that done tonight an submit a PR

**Comment by msroest** [comment]
Think that should do it I've tested with and without mailname and TLS settings.
